# Generated by Django 5.2.4 on 2025-07-26 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdefinition',
            name='booking_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot_definition', to='core.bookingpage'),
        ),
    ]
